auto: true
uyan: xumenger
markdown: kramdown
kramdown:
       input: GFM
       hard_wrap: false
pygments: true
paginate: 8
permalink: /:title

title: 小白的狗窝
url: http://xiaobaiso.github.io/
feed: /atom.xml
author_info: <a href="http://xiaobaiso.github.io/">Xiaobaiso</a>
