# Basic
title: 小白的技术宅
subtitle: 遇见更好的自己.
welcome_message: <a href="http://xiaobaiso.me">这是我用来记录生活和技术的地方，欢迎你的访问.</a>
description: 嗨，我是小白，从事iOS相关的工作，目前暂居深圳.
creator: <a href="http://xiaobaiso.me">@xiaobaiso</a>

url: "http://xiaobaiso.github.io"

permalink: /blog/:title.html

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 了解相关项目, url: 'http://github.com/xiaobaiso'}
    - {title: 临时邮说明, description: 临时邮, url: 'https://xiaobaiso.github.io/tempmail/'}
    - {title: 临时邮, description: 临时邮, url: 'https://itunes.apple.com/cn/app/%E4%B8%B4%E6%97%B6%E9%82%AE-%E5%8D%81%E5%88%86%E9%92%9F%E9%82%AE%E7%AE%B1/id1342693449?mt=8'}
    - {title: 知乎视频爬虫, description: 视频下载小助手, url: 'https://xiaobaiso.github.io/zhihudoc/'}
# - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
#comment:
    #disqus: vno-jekyll
    # duoshuo:

# Social
social:
    #weibo: devzeng
    github: xiaobaiso
    #twitter: hhtczengjing
    #gplus: 107108267983477358170
    mail: xbcoding@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
