# Basic
title: 小白的技术宅
subtitle: 遇见更好的自己.
welcome_message: 这是我用来记录生活和技术的地方，欢迎你的访问.
description: 嗨，我是小白，从事Linux以及iOS相关的工作，目前暂居深圳。
creator: <a href="http://xiaobaiso.me">@xiaobaiso</a>

url: "http://xiaobaiso.github.io"

permalink: /blog/:title.html

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 了解相关项目, url: 'http://github.com/xiaobaiso'}
    - {title: 关于, description: 了解更多关于我, url: '#'}    
# - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
#comment:
    #disqus: vno-jekyll
    # duoshuo:

# Social
social:
    #weibo: devzeng
    github: xiaobaiso
    #twitter: hhtczengjing
    #gplus: 107108267983477358170
    mail: xbcoding@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
